# Generated by Django 2.2.22 on 2021-10-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannermodel',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='bannermodel',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
