# Generated by Django 2.2.2 on 2021-09-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
